### ISSUE TITLE
Diagrams in preview

### ISSUE THREAD

**Issue by tinysun212** [dzruyk/obsidian-asciidoc#2]
Is it possible to make a mermaid diagram like the one below visible in the preview? 

```
[mermaid]
----
flowchart LR
A --> B
----
```

**Comment by dzruyk** [comment]
Done in [0.1.3](https://github.com/dzruyk/obsidian-asciidoc/releases/tag/0.1.3)
But according to [asciidoc docs ](https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/) you should use this syntax

```
[,mermaid]
----
flowchart LR
A --> B
----
OR
[source,mermaid]
----
flowchart LR
A --> B
----
```

**Comment by tinysun212** [comment]
Thank you so much for your help!

By the way, have you thought about using Kroki to create diagrams, like PlantUML diagrams?

**Comment by dzruyk** [comment]
I think there should be a simple way to integrate other plugins that implement additional code blocks processing (such as [obsidian-plantuml](https://github.com/joethei/obsidian-plantuml)).

From the obsidian-asciidoc side, you will need to add a new handler here [asciidocView.ts](https://github.com/dzruyk/obsidian-asciidoc/blob/master/src/asciidocView.ts#L332) and use other plugin's pulic API from `app.plugins.plugins['PLUGIN_ID_NAME']` and postprocess code block.

However, I have no plans to implement this in the near future.

**Comment by tinysun212** [comment]
> Done in [0.1.3](https://github.com/dzruyk/obsidian-asciidoc/releases/tag/0.1.3) But according to [asciidoc docs ](https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/) you should use this syntax
> 
> ```
> [,mermaid]
> ----
> flowchart LR
> A --> B
> ----
> OR
> [source,mermaid]
> ----
> flowchart LR
> A --> B
> ----
> ```

AsciiDoctor supports [diagram blocks](https://docs.asciidoctor.org/diagram-extension/latest/blocks/), which are compatible with GitHub, GitLab, and the AsciiDoc plugin for VS Code (by asciidoctor.org). Note that these are not source blocks.

Could you modify it to be compatible with them?

**Comment by dzruyk** [comment]
Ok, I will try

**Comment by dzruyk** [comment]
@tinysun212.
I Added the `[mermaid]` block in version 0.1.5.

I was trying to add kroki support to the plugin (the `kroki` branch in this repository). I used [asciidoctor-kroki](https://github.com/asciidoctor/asciidoctor-kroki) module for this purpose.

But there are a couple of issues with kroki. And I don't think adding changes to the master branch is a good idea:
- The size of the source code in main.js increases several times (because of `asciidoctor-kroki` module is quite large)
- Every time kroki diagram is rendered in the reading-view, access to the kroki server is required.  

The last problem is rather technical, it seems kroki can be deployed locally, In addition, our plugin can somehow cache diagrams so as not to redraw the old ones.
But I won't be doing this in the near future. However, you can try using the plugin version from the `kroki` branch if you like.

**Comment by tinysun212** [comment]
Thanks a bunch! I went ahead and installed the branch. I’m currently using it with my local Kroki server.
